# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'childPuzzle' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for childPuzzle
  pod 'SQLite.swift', '~> 0.10.1'
end
